# Generated by Django 5.2.16 on 2026-07-19 20:25

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'payment_sequences',
            },
        ),
        migrations.CreateModel(
            name='IntegratedPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay')], db_index=True, max_length=20)),
                ('provider_account_reference', models.CharField(blank=True, max_length=120)),
                ('connection_status', models.CharField(choices=[('not_connected', 'Not Connected'), ('setup_required', 'Setup Required'), ('verification_pending', 'Verification Pending'), ('connected', 'Connected'), ('restricted', 'Restricted'), ('disconnected', 'Disconnected')], db_index=True, default='not_connected', max_length=20)),
                ('verification_status', models.CharField(blank=True, max_length=40)),
                ('account_type', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('supported_currencies', models.JSONField(blank=True, default=list)),
                ('last_connection_check', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrated_payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrated_payment_accounts',
            },
        ),
        migrations.CreateModel(
            name='ManualPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('upi', 'UPI'), ('google_pay', 'Google Pay'), ('phonepe', 'PhonePe'), ('paytm', 'Paytm'), ('bank_transfer', 'Bank Transfer'), ('zelle', 'Zelle'), ('venmo', 'Venmo'), ('cash_app', 'Cash App'), ('paypal_manual', 'PayPal (manual transfer)'), ('cash', 'Cash'), ('other', 'Other')], db_index=True, max_length=20)),
                ('display_label', models.CharField(max_length=120)),
                ('supported_currencies', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('private_fields', models.JSONField(blank=True, default=dict)),
                ('client_visible_fields', models.JSONField(blank=True, default=dict)),
                ('qr_code', models.FileField(blank=True, null=True, upload_to='payments/qr-codes/%Y/%m/')),
                ('internal_notes', models.TextField(blank=True)),
                ('client_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payment_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_payment_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPaymentMethodAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_access', to='accounts.clientaccess')),
                ('payment_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access_grants', to='accounts.manualpaymentprofile')),
            ],
            options={
                'db_table': 'client_payment_method_access',
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('professional', 'Professional'), ('client', 'Client')], db_index=True, max_length=12)),
                ('notif_type', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to='accounts.clientaccess')),
                ('recipient_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('billing_cycle', models.CharField(choices=[('one_time', 'One time'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('custom', 'Custom')], default='monthly', max_length=12)),
                ('installment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_currency', models.CharField(max_length=3)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('payment_type', models.CharField(choices=[('manual', 'Manual'), ('integrated', 'Integrated'), ('both', 'Both')], default='manual', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('proof_submitted', 'Proof Submitted'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('partially_paid', 'Partially Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20)),
                ('client_visibility', models.CharField(choices=[('private', 'Private'), ('visible', 'Visible to client')], default='visible', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='accounts.clientaccess')),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='accounts.paymentplan')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_record_id', models.CharField(db_index=True, default=accounts.models.generate_payment_record_id, editable=False, max_length=32, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_currency', models.CharField(max_length=3)),
                ('reporting_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reporting_currency', models.CharField(max_length=3)),
                ('exchange_rate_reference', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('exchange_rate_source', models.CharField(blank=True, default='manual', max_length=40)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('received_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('partially_paid', 'Partially Paid'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=14)),
                ('client_visibility', models.CharField(choices=[('private', 'Private'), ('visible', 'Visible to client')], default='visible', max_length=12)),
                ('internal_note', models.TextField(blank=True)),
                ('client_note', models.TextField(blank=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payments/records/%Y/%m/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='accounts.clientaccess')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='accounts.manualpaymentprofile')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payment_records', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='accounts.paymentrequest')),
            ],
            options={
                'db_table': 'payment_records',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(blank=True, max_length=150)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('reported_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reported_currency', models.CharField(max_length=3)),
                ('reported_payment_date', models.DateField()),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payments/proofs/%Y/%m/')),
                ('note', models.TextField(blank=True)),
                ('confirmed_accurate', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=14)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs', to='accounts.manualpaymentprofile')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='accounts.paymentrequest')),
            ],
            options={
                'db_table': 'payment_proofs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('method_created', 'Method created'), ('method_updated', 'Method updated'), ('method_shared', 'Method shared'), ('method_unshared', 'Method unshared'), ('request_created', 'Request created'), ('request_cancelled', 'Request cancelled'), ('proof_submitted', 'Proof submitted'), ('proof_rejected', 'Proof rejected'), ('info_requested', 'More info requested'), ('payment_verified', 'Payment verified'), ('payment_recorded', 'Payment recorded'), ('payment_edited', 'Payment edited'), ('payment_deleted', 'Payment deleted')], db_index=True, max_length=32)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.CharField(blank=True, max_length=180)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to='accounts.clientaccess')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('payment_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.paymentrecord')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.paymentrequest')),
            ],
            options={
                'db_table': 'payment_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequestAllowedMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrated_payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_on_requests', to='accounts.integratedpaymentaccount')),
                ('manual_payment_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_on_requests', to='accounts.manualpaymentprofile')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_methods', to='accounts.paymentrequest')),
            ],
            options={
                'db_table': 'payment_request_allowed_methods',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_currency', models.CharField(default='USD', max_length=3)),
                ('client_payment_history_enabled', models.BooleanField(default=True)),
                ('default_payment_visibility', models.CharField(choices=[('private', 'Private'), ('visible', 'Visible to client')], default='private', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_payment_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='integratedpaymentaccount',
            constraint=models.UniqueConstraint(fields=('professional', 'provider'), name='one_account_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='clientpaymentmethodaccess',
            constraint=models.UniqueConstraint(fields=('client', 'payment_profile'), name='one_grant_per_client_method'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['professional', 'status'], name='pay_req_prof_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['client', 'status'], name='pay_req_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['professional', 'received_date'], name='pay_rec_prof_date_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['client', 'status'], name='pay_rec_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['professional', 'created_at'], name='pay_audit_prof_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequestallowedmethod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('integrated_payment_account__isnull', True), ('manual_payment_profile__isnull', False)), models.Q(('integrated_payment_account__isnull', False), ('manual_payment_profile__isnull', True)), _connector='OR'), name='payment_allowed_method_one_target'),
        ),
    ]
