# Generated by Django 5.2.16 on 2026-07-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalpaymentsettings',
            name='payment_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
