# Generated by Django 5.2.15 on 2026-07-21 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_chat_message_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('chat_message', 'Chat message'), ('tracking_entry', 'Tracking entry'), ('progress_entry', 'Progress entry'), ('reminder', 'Reminder'), ('reference', 'Reference'), ('template', 'Template')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('deleted_by', models.CharField(choices=[('professional', 'Professional'), ('retention_policy', 'Retention policy')], default='professional', max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_bin_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recycle_bin_items',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
