# Generated by Django 5.2.15 on 2026-07-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_recycle_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclebinitem',
            name='category',
            field=models.CharField(choices=[('chat_message', 'Chat message'), ('reference', 'Reference'), ('client_account', 'Client account')], db_index=True, max_length=20),
        ),
    ]
