# Generated by Django 5.2.16 on 2026-07-08 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_clientaccess_is_active_clientaccess_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to="accounts.clientaccess",
                    ),
                ),
            ],
            options={
                "db_table": "client_auth_tokens",
            },
        ),
        migrations.CreateModel(
            name="ReferenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("subcategories", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reference_categories",
                "ordering": ["created_at"],
                "unique_together": {("trainer", "name")},
            },
        ),
        migrations.CreateModel(
            name="TrainerReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=180)),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("video_link", "Video Link"),
                            ("pdf", "PDF"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("text_note", "Text Note"),
                            ("external_link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True)),
                ("file", models.FileField(blank=True, upload_to="trainer-references/")),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="references",
                        to="accounts.referencecategory",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_references",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trainer_references",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("purpose", models.TextField(blank=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "accent",
                    models.CharField(blank=True, default="green", max_length=20),
                ),
                ("fields", models.JSONField(default=list)),
                ("standard_key", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "references",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tracking_templates",
                        to="accounts.trainerreference",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_templates",
                "ordering": ["created_at"],
                "unique_together": {("trainer", "name")},
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("trainer", "Trainer"), ("client", "Client")],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="accounts.clientaccess",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "created_at"],
                        name="chat_messag_client__9f96f9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=120)),
                ("entry_date", models.DateField()),
                ("answers", models.JSONField(default=dict)),
                ("note", models.TextField(blank=True)),
                ("edited_by_trainer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_entries",
                        to="accounts.clientaccess",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="accounts.trackingtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_entries",
                "ordering": ["-entry_date", "-updated_at"],
                "unique_together": {("client", "template", "entry_date")},
            },
        ),
        migrations.CreateModel(
            name="TemplateAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_assignments",
                        to="accounts.clientaccess",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="accounts.trackingtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "template_assignments",
                "ordering": ["assigned_at"],
                "unique_together": {("client", "template")},
            },
        ),
    ]
