# Generated by Django 5.2.15 on 2026-07-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_simplify_recycle_bin_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalpaymentsettings',
            name='reporting_currency_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='professionalpaymentsettings',
            name='default_payment_visibility',
            field=models.CharField(choices=[('private', 'Private'), ('visible', 'Visible to client')], default='visible', max_length=12),
        ),
    ]
