# Generated by Django 5.2.15 on 2026-07-21 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_payment_currency_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalComConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('cal_username', models.CharField(blank=True, max_length=150)),
                ('default_event_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('default_event_type_slug', models.CharField(blank=True, max_length=150)),
                ('default_event_type_label', models.CharField(blank=True, max_length=180)),
                ('default_duration_minutes', models.PositiveIntegerField(default=30)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_connected', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cal_com_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cal_com_connections',
            },
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meeting', max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('meeting_url', models.URLField(blank=True)),
                ('cal_booking_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='scheduled', max_length=12)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='accounts.clientaccess')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_meetings',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['professional', 'start_at'], name='meeting_prof_start_idx'), models.Index(fields=['client', 'start_at'], name='meeting_client_start_idx')],
            },
        ),
    ]
