# Generated by Django 5.2.16 on 2026-07-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_clientauthtoken_referencecategory_trainerreference_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackingtemplate",
            name="references",
        ),
        migrations.AddField(
            model_name="templateassignment",
            name="references",
            field=models.ManyToManyField(
                blank=True,
                related_name="template_assignments",
                to="accounts.trainerreference",
            ),
        ),
    ]
