# Generated by Django 5.2.16 on 2026-07-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_remove_trackingtemplate_references_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientaccess",
            name="trainer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="clientaccess",
            name="trainer_notes_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
