# Generated by Django 5.2.15 on 2026-07-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='client_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='client_response_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='ScheduledMeetingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meeting_guest_spots', to='accounts.clientaccess')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='accounts.scheduledmeeting')),
            ],
            options={
                'db_table': 'scheduled_meeting_guests',
                'constraints': [models.UniqueConstraint(fields=('meeting', 'client'), name='unique_meeting_guest')],
            },
        ),
    ]
