# Generated by Django 5.2.16 on 2026-07-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clientaccess_trainer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='trainer_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
