# Generated by Django 5.2.15 on 2026-07-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_scheduledmeeting_client_responded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentauditlog',
            name='action',
            field=models.CharField(choices=[('method_created', 'Method created'), ('method_updated', 'Method updated'), ('method_shared', 'Method shared'), ('method_unshared', 'Method unshared'), ('request_created', 'Request created'), ('request_cancelled', 'Request cancelled'), ('proof_submitted', 'Proof submitted'), ('proof_rejected', 'Proof rejected'), ('info_requested', 'More info requested'), ('payment_acknowledged', 'Payment acknowledged'), ('payment_verified', 'Payment verified'), ('payment_recorded', 'Payment recorded'), ('payment_edited', 'Payment edited'), ('payment_deleted', 'Payment deleted')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('proof_submitted', 'Proof Submitted'), ('under_review', 'Under Review'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed'), ('partially_paid', 'Partially Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20),
        ),
    ]
