# Generated by Django 5.2.15 on 2026-07-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_seed_universal_client_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingentry',
            options={'ordering': ['-entry_date', '-entry_time', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='trackingentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trackingentry',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientDetailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('client_note', models.TextField(blank=True)),
                ('trainer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_change_requests', to='accounts.clientaccess')),
            ],
            options={
                'db_table': 'client_detail_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
