# Generated by Django 5.2.15 on 2026-07-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_trackingentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccess',
            name='photo',
            field=models.TextField(blank=True),
        ),
    ]
