# Generated by Django 5.2.16 on 2026-07-22
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [('accounts', '0015_lead_introductory_meetings'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
  operations = [
    migrations.CreateModel(name='ActivityNotification', fields=[
      ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
      ('recipient_type', models.CharField(choices=[('professional','Professional'),('client','Client'),('admin','Admin')], db_index=True, max_length=16)),
      ('admin_scope', models.CharField(blank=True, db_index=True, max_length=24)), ('category', models.CharField(db_index=True, max_length=32)),
      ('event_type', models.CharField(db_index=True, max_length=80)), ('event_key', models.CharField(max_length=180, unique=True)),
      ('title', models.CharField(max_length=200)), ('body', models.TextField(blank=True)), ('action_url', models.CharField(blank=True, max_length=300)),
      ('payload', models.JSONField(blank=True, default=dict)), ('priority', models.CharField(choices=[('info','Info'),('normal','Normal'),('high','High'),('critical','Critical')], default='normal', max_length=10)),
      ('requires_action', models.BooleanField(default=False)), ('is_read', models.BooleanField(db_index=True, default=False)),
      ('read_at', models.DateTimeField(blank=True, null=True)), ('acknowledged_at', models.DateTimeField(blank=True, null=True)), ('resolved_at', models.DateTimeField(blank=True, null=True)),
      ('email_status', models.CharField(choices=[('suppressed','Suppressed'),('pending','Pending'),('sent','Sent'),('failed','Failed')], db_index=True, default='suppressed', max_length=12)),
      ('push_status', models.CharField(choices=[('suppressed','Suppressed'),('pending','Pending'),('sent','Sent'),('failed','Failed')], db_index=True, default='suppressed', max_length=12)),
      ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
      ('recipient_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notifications', to='accounts.clientaccess')),
      ('recipient_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_notifications', to=settings.AUTH_USER_MODEL)),
    ], options={'db_table':'activity_notifications','ordering':['-created_at']}),
    migrations.CreateModel(name='NotificationDeliveryAttempt', fields=[
      ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
      ('channel', models.CharField(choices=[('email','Email'),('push','Push')], max_length=12)), ('status', models.CharField(choices=[('suppressed','Suppressed'),('pending','Pending'),('sent','Sent'),('failed','Failed')], max_length=12)),
      ('provider_message_id', models.CharField(blank=True, max_length=200)), ('error', models.TextField(blank=True)), ('attempted_at', models.DateTimeField(auto_now_add=True)),
      ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='accounts.activitynotification')),
    ], options={'db_table':'notification_delivery_attempts','ordering':['-attempted_at']}),
    migrations.CreateModel(name='NotificationPreference', fields=[
      ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
      ('recipient_type', models.CharField(choices=[('professional','Professional'),('client','Client')], max_length=16)), ('category', models.CharField(max_length=32)),
      ('in_app_enabled', models.BooleanField(default=True)), ('email_enabled', models.BooleanField(default=False)), ('push_enabled', models.BooleanField(default=True)),
      ('digest_frequency', models.CharField(choices=[('immediate','Immediate'),('daily','Daily'),('weekly','Weekly'),('monthly','Monthly'),('none','None')], default='immediate', max_length=12)), ('updated_at', models.DateTimeField(auto_now=True)),
      ('recipient_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='accounts.clientaccess')),
      ('recipient_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
    ], options={'db_table':'notification_preferences'}),
    migrations.AddIndex(model_name='activitynotification', index=models.Index(fields=['recipient_type','is_read','created_at'], name='activity_recipient_unread_idx')),
    migrations.AddConstraint(model_name='notificationpreference', constraint=models.UniqueConstraint(fields=('recipient_type','recipient_professional','category'), name='uniq_prof_notification_pref')),
    migrations.AddConstraint(model_name='notificationpreference', constraint=models.UniqueConstraint(fields=('recipient_type','recipient_client','category'), name='uniq_client_notification_pref')),
  ]
