# Generated by Django 5.2.15 on 2026-07-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_clientaccess_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccess',
            name='additional_info',
            field=models.JSONField(default=list),
        ),
    ]
