# Generated by Django 5.2.16 on 2026-07-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_shared_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistrationform',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professionalleadform',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
