# Generated by Django 5.2.15 on 2026-07-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_clientaccess_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
