# Generated by Django 5.2.16 on 2026-07-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_clientregistrationform_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccess',
            name='has_portal_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientaccess',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clientaccess',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
