# Generated by Django 5.2.16 on 2026-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_clientaccess_has_portal_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateassignment',
            name='client_access_level',
            field=models.CharField(choices=[('private', 'Private'), ('view_only', 'View only'), ('editable', 'Editable')], default='editable', max_length=20),
        ),
    ]
