# Generated by Django 5.2.16 on 2026-07-23 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_templateassignment_client_access_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmeetingrequest',
            name='ics_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='ics_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProfessionalAvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Monday .. 6=Sunday, matching date.weekday().')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_availability_windows',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSchedulingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_duration_minutes', models.PositiveIntegerField(default=30)),
                ('slot_interval_minutes', models.PositiveIntegerField(default=30)),
                ('buffer_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_scheduling_settings',
            },
        ),
        migrations.DeleteModel(
            name='CalComConnection',
        ),
    ]
