# Generated by Django 5.2.15 on 2026-07-10 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_trainerprofile_profile_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccess',
            name='additional_info_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClientReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], db_index=True, default='pending', max_length=20)),
                ('notify_trainer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.clientaccess')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_reminders',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('next_step', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='accounts.clientaccess')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
