# Generated by Django 5.2.15 on 2026-07-13 19:03

import uuid

import accounts.models
from django.db import migrations, models


def populate_internal_references(apps, schema_editor):
    TrainerProfile = apps.get_model('accounts', 'TrainerProfile')
    for profile in TrainerProfile.objects.all().iterator():
        TrainerProfile.objects.filter(pk=profile.pk).update(
            internal_reference_code=f'TRN-{uuid.uuid4().hex[:10].upper()}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_manual_and_group_client_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='internal_reference_code',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.RunPython(
            populate_internal_references,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='internal_reference_code',
            field=models.CharField(db_index=True, default=accounts.models.generate_trainer_internal_reference, editable=False, max_length=24, unique=True),
        ),
    ]
