# Generated by Django 5.2.15 on 2026-07-14 18:44

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_plan_tier_and_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetailchangerequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetailchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, default=accounts.models.support_incident_reference, editable=False, max_length=24, unique=True)),
                ('reporter_role', models.CharField(choices=[('trainer', 'Trainer'), ('client', 'Client')], db_index=True, max_length=12)),
                ('reporter_name', models.CharField(max_length=180)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('feedback', 'Feedback'), ('bug_report', 'Bug report'), ('account_issue', 'Account issue'), ('payment_subscription', 'Payment or subscription issue'), ('feature_request', 'Feature request'), ('technical_problem', 'Technical problem'), ('other', 'Other issue')], db_index=True, max_length=32)),
                ('subject', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('page_feature', models.CharField(blank=True, max_length=180)),
                ('platform', models.CharField(default='web', max_length=24)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('device_info', models.CharField(blank=True, max_length=300)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='support-incidents/%Y/%m/')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=12)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('open', 'Open'), ('under_review', 'Under review'), ('waiting_for_user', 'Waiting for user'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], db_index=True, default='submitted', max_length=24)),
                ('resolution_note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_incidents', to='accounts.clientaccess')),
                ('reporter_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_incidents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportIncidentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('user', 'Reporter'), ('support', 'Support'), ('internal', 'Internal note')], db_index=True, max_length=12)),
                ('author_name', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_incident_messages', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.supportincident')),
            ],
            options={
                'db_table': 'support_incident_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportincident',
            index=models.Index(fields=['reporter_role', 'status'], name='support_role_status_idx'),
        ),
    ]
