# Generated by Django 5.2.16 on 2026-07-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_subscription_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='google_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, help_text='Stable Google account identifier ("sub" claim) linked for Google sign-in, if any.', max_length=64, null=True, unique=True),
        ),
    ]
