# Generated by Django 5.2.16 on 2026-07-29 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_professionalprofile_google_linked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDateOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_date_offs',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('professional', 'date'), name='unique_professional_date_off')],
            },
        ),
    ]
