# Generated by Django 5.2.16 on 2026-07-29 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_professional_date_off'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalWeekdayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_offs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_weekday_offs',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('professional', 'weekday'), name='unique_professional_weekday_off')],
            },
        ),
    ]
