# Hand-written (not autogenerated): Django's makemigrations cannot detect
# renames non-interactively, so a plain `makemigrations` run here would emit
# DeleteModel/CreateModel pairs that DROP the reference_categories /
# professional_references tables and lose all existing data. This migration
# instead uses RenameModel/RenameField/AlterModelTable so the underlying
# tables and columns are renamed in place, preserving data. A RunPython data
# migration at the end fixes up RecycleBinItem rows that still have the old
# 'reference' category value stored so previously soft-deleted resources
# remain restorable.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


OLD_CATEGORY_VALUE = 'reference'
NEW_CATEGORY_VALUE = 'resource'


def forwards_fix_recycle_bin_category(apps, schema_editor):
  RecycleBinItem = apps.get_model('accounts', 'RecycleBinItem')
  RecycleBinItem.objects.filter(category=OLD_CATEGORY_VALUE).update(category=NEW_CATEGORY_VALUE)


def backwards_fix_recycle_bin_category(apps, schema_editor):
  RecycleBinItem = apps.get_model('accounts', 'RecycleBinItem')
  RecycleBinItem.objects.filter(category=NEW_CATEGORY_VALUE).update(category=OLD_CATEGORY_VALUE)


class Migration(migrations.Migration):

  dependencies = [
    ('accounts', '0027_professionalweekdayoff'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    # --- ReferenceCategory -> ResourceCategory ---
    migrations.RenameModel(old_name='ReferenceCategory', new_name='ResourceCategory'),
    migrations.AlterModelTable(name='resourcecategory', table='resource_categories'),
    migrations.AlterField(
      model_name='resourcecategory',
      name='professional',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to=settings.AUTH_USER_MODEL),
    ),

    # --- ProfessionalReference -> ProfessionalResource ---
    migrations.RenameModel(old_name='ProfessionalReference', new_name='ProfessionalResource'),
    migrations.AlterModelTable(name='professionalresource', table='professional_resources'),
    migrations.RenameField(model_name='professionalresource', old_name='reference_type', new_name='resource_type'),
    migrations.AlterField(
      model_name='professionalresource',
      name='category',
      field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='accounts.resourcecategory'),
    ),
    migrations.AlterField(
      model_name='professionalresource',
      name='professional',
      field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_resources', to=settings.AUTH_USER_MODEL),
    ),
    migrations.AlterField(
      model_name='professionalresource',
      name='file',
      field=models.FileField(blank=True, upload_to='professional-resources/'),
    ),

    # --- TemplateAssignment.references (M2M) -> resources ---
    migrations.RenameField(model_name='templateassignment', old_name='references', new_name='resources'),

    # --- RecycleBinItem.category choices label/value update ---
    migrations.AlterField(
      model_name='recyclebinitem',
      name='category',
      field=models.CharField(
        choices=[('chat_message', 'Chat message'), ('resource', 'Resource'), ('client_account', 'Client account')],
        db_index=True,
        max_length=20,
      ),
    ),
    migrations.RunPython(forwards_fix_recycle_bin_category, backwards_fix_recycle_bin_category),
  ]
