# Generated by Django 5.2.16 on 2026-07-30 14:44

from django.db import migrations, models


# Backfill priority_rank for every existing row, per professional, in
# created_at order -- this establishes the "oldest first" default ranking
# the plan-limit lock system relies on before anyone has ever reordered
# anything. New rows get assigned the next available rank at creation time
# going forward (see accounts/plan_lock_status.py).
MODELS_TO_BACKFILL = [
  ('ProfessionalGroup', 'professional_id'),
  ('ProfessionalLeadForm', 'professional_id'),
  ('ProfessionalResource', 'professional_id'),
  ('ResourceCategory', 'professional_id'),
  ('TrackingTemplate', 'professional_id'),
]


def forwards_backfill_priority_rank(apps, schema_editor):
  for model_name, owner_field in MODELS_TO_BACKFILL:
    Model = apps.get_model('accounts', model_name)
    owners = Model.objects.order_by().values_list(owner_field, flat=True).distinct()
    for owner_id in owners:
      rows = Model.objects.filter(**{owner_field: owner_id}).order_by('created_at', 'id')
      for rank, row in enumerate(rows):
        row.priority_rank = rank
        row.save(update_fields=['priority_rank'])


def backwards_clear_priority_rank(apps, schema_editor):
  for model_name, _owner_field in MODELS_TO_BACKFILL:
    Model = apps.get_model('accounts', model_name)
    Model.objects.update(priority_rank=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_rename_notification_preference_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalgroup',
            name='priority_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalleadform',
            name='priority_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalresource',
            name='priority_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='priority_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingtemplate',
            name='priority_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(forwards_backfill_priority_rank, backwards_clear_priority_rank),
    ]
