# Generated by Django 5.2.16 on 2026-07-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_plan_lock_priority_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccess',
            name='suspended_by_plan_lock',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
