# Generated by Django 5.2.16 on 2026-07-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_client_suspended_by_plan_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='cancellation_target_tier',
            field=models.CharField(blank=True, choices=[('starter_free', 'Starter Free'), ('pro', 'Pro'), ('premium_unlimited', 'Premium Unlimited'), ('starter', 'Starter (Legacy)'), ('premium', 'Premium (Legacy)')], default='', max_length=20),
        ),
    ]
