# Generated by Django 5.2.16 on 2026-07-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_legaldocumentrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('proof_submitted', 'Proof Submitted'), ('under_review', 'Under Review'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed'), ('partially_paid', 'Partially Paid'), ('overpaid', 'Overpaid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20),
        ),
    ]
