import { CurrencyPipe, DatePipe } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AdminFinanceSummary, AdminPortalApiService } from '@core/api/admin-portal-api.service';
import { AdminPageShellComponent } from '@admin-shared/admin-page-shell/admin-page-shell.component';
import { formatApiError } from '@shared/utils/ui-helpers';

@Component({selector:'app-admin-finance',standalone:true,imports:[AdminPageShellComponent,FormsModule,CurrencyPipe,DatePipe],template:`
<app-admin-page-shell title="Finance" subtitle="Permission-controlled financial summaries and ledger activity." activeSection="finance">
  <label page-actions class="range">Date range<select [(ngModel)]="range" (change)="load()"><option value="today">Today</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="90d">Last 90 Days</option></select></label>
  @if(message){<p class="message">{{message}}</p>}
  @if(summary){<section class="notice"><div><p class="eyebrow">Integration status</p><h2>{{summary.finance_tracking_status}}</h2><p>Billing provider: {{summary.billing_provider}}. No payment credentials or full payment data are stored here.</p></div><span>{{summary.currency}}</span></section>
  <section class="finance-kpis"><article><small>Gross revenue</small><strong>{{+summary.summary.gross_revenue|currency:summary.currency}}</strong></article><article><small>Completed transactions</small><strong>{{summary.summary.completed_transactions}}</strong></article><article><small>Pending</small><strong>{{summary.summary.pending_transactions}}</strong></article><article class="warning"><small>Failed</small><strong>{{summary.summary.failed_transactions}}</strong></article><article><small>Refunds</small><strong>{{+summary.summary.refund_total|currency:summary.currency}}</strong></article></section>
  <section class="ledger"><div class="section-head"><div><p class="eyebrow">Ledger</p><h2>Recent activity</h2></div><span>{{summary.recent_entries.length}} records</span></div>@if(summary.recent_entries.length){<div class="table-wrap"><table><thead><tr><th>Entry</th><th>Professional</th><th>Type</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead><tbody>@for(entry of summary.recent_entries;track entry.entry_id){<tr><td>{{entry.entry_id}}</td><td>{{entry.professional_display}}</td><td>{{entry.entry_type}}</td><td><span class="badge">{{entry.status}}</span></td><td>{{+entry.amount|currency:entry.currency}}</td><td>{{entry.occurred_at|date:'medium'}}</td></tr>}</tbody></table></div>}@else{<div class="empty"><strong>No finance entries yet</strong><p>The page is ready for a future billing provider. Values remain zero until verified ledger events are recorded.</p></div>}</section>}
</app-admin-page-shell>`,styles:[`
.range{display:flex;align-items:center;gap:.6rem;color:var(--app-muted);font-size:.8rem;font-weight:700}.range select{min-height:2.3rem}.message{color:#b42318}.notice,.ledger{border:1px solid var(--app-border);border-radius:.9rem;padding:1.2rem;background:var(--app-surface);box-shadow:var(--app-shadow-sm)}.notice{display:flex;justify-content:space-between;align-items:center}.notice h2{margin:0}.notice p:not(.eyebrow){margin:.3rem 0 0;color:var(--app-muted)}.notice>span{border-radius:2rem;padding:.45rem .8rem;background:var(--app-primary-soft);color:var(--app-primary-strong);font-weight:800}.finance-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:.7rem;margin:1rem 0}.finance-kpis article{display:grid;gap:.25rem;border:1px solid var(--app-border);border-radius:.75rem;padding:1rem;background:var(--app-surface)}article small{color:var(--app-muted);font-weight:700}article strong{font-size:1.45rem}.warning strong{color:#b42318}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:1rem}.section-head h2{margin:0}.section-head span{color:var(--app-muted)}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid var(--app-border);padding:.75rem;text-align:left;white-space:nowrap}th{color:var(--app-muted);font-size:.7rem;text-transform:uppercase}.badge{border-radius:2rem;padding:.3rem .55rem;background:var(--app-surface-soft);font-size:.7rem;font-weight:800}.empty{padding:3rem;text-align:center;background:var(--app-surface-soft);border-radius:.75rem}.empty p{color:var(--app-muted)}@media(max-width:950px){.finance-kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.finance-kpis{grid-template-columns:1fr 1fr}}
`]})
export class AdminFinanceComponent implements OnInit{range='30d';summary?:AdminFinanceSummary;message='';constructor(private api:AdminPortalApiService){}ngOnInit():void{this.load()}load():void{this.api.getFinance(this.range).subscribe({next:value=>{this.summary=value;this.message=''},error:error=>this.message=formatApiError(error,'Finance summary could not be loaded.')})}}
