import { CommonModule, DatePipe, DecimalPipe } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AdminFinanceEntry, AdminFinanceSummary, AdminPortalApiService } from '@core/api/admin-portal-api.service';
import { AdminPageShellComponent } from '@admin-shared/admin-page-shell/admin-page-shell.component';
import { formatApiError } from '@shared/utils/ui-helpers';

@Component({selector:'app-admin-finance',standalone:true,imports:[AdminPageShellComponent,FormsModule,CommonModule,DatePipe,DecimalPipe],template:`
<app-admin-page-shell title="Finance" subtitle="RepRoot subscription revenue, platform commissions, refunds and operating expenses only." activeSection="finance">
 <div page-actions class="filters"><select [(ngModel)]="range" (change)="load()"><option value="30d">30 days</option><option value="90d">90 days</option><option value="365d">1 year</option><option value="lifetime">Lifetime</option><option value="custom">Custom</option></select>@if(range==='custom'){<input type="date" [(ngModel)]="startDate" (change)="load()"><input type="date" [(ngModel)]="endDate" (change)="load()">}</div>
 @if(message){<p class="message">{{message}}</p>}
 @if(summary){
  <section class="notice"><div><p class="eyebrow">Business boundary</p><h2>RepRoot money only</h2><p>Private trainer/client payment volume is excluded. Revenue below comes only from subscriptions, RepRoot commissions and explicit business ledger entries.</p></div></section>
  <div class="money-grid"><section><h3>Revenue by currency</h3>@for(item of money(summary.summary.revenue_by_currency);track item.currency){<strong>{{item.currency}} {{item.amount|number:'1.2-2'}}</strong>}@empty{<span>No revenue recorded</span>}</section><section><h3>Expenses by currency</h3>@for(item of money(summary.summary.expense_by_currency);track item.currency){<strong>{{item.currency}} {{item.amount|number:'1.2-2'}}</strong>}@empty{<span>No expenses recorded</span>}</section><section><h3>Activity</h3><strong>{{summary.summary.completed_transactions}} completed</strong><span>{{summary.summary.pending_transactions}} pending · {{summary.summary.failed_transactions}} failed</span></section></div>
  @if(canEdit){<section class="expense-form"><div><p class="eyebrow">Manual record</p><h2>Add operating expense</h2></div><div class="form-grid"><label>Amount<input type="number" min="0.01" step="0.01" [(ngModel)]="expense.amount"></label><label>Currency<select [(ngModel)]="expense.currency"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>AUD</option><option>CAD</option></select></label><label>Category<select [(ngModel)]="expense.category"><option value="INFRASTRUCTURE">Infrastructure</option><option value="SOFTWARE">Software</option><option value="MARKETING">Marketing</option><option value="PAYROLL">Payroll / contractors</option><option value="PROFESSIONAL_SERVICES">Professional services</option><option value="OTHER">Other</option></select></label><label>Date<input type="date" [(ngModel)]="expense.expense_date"></label><label>Vendor<input [(ngModel)]="expense.vendor"></label><label class="wide">Description<input [(ngModel)]="expense.description"></label></div><button type="button" (click)="saveExpense()">Record expense</button></section>}
  <section class="ledger"><h2>Subscription purchases</h2><ng-container *ngTemplateOutlet="ledger;context:{entries:summary.subscriptions}"></ng-container></section>
  <section class="ledger"><h2>RepRoot commissions</h2><ng-container *ngTemplateOutlet="ledger;context:{entries:summary.commissions}"></ng-container></section>
  <section class="ledger"><h2>Operating expenses</h2>@if(summary.expenses.length){<div class="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Vendor</th><th>Description</th><th>Amount</th></tr></thead><tbody>@for(item of summary.expenses;track item.expense_id){<tr><td>{{item.expense_date|date}}</td><td>{{item.category_label}}</td><td>{{item.vendor||'—'}}</td><td>{{item.description}}</td><td>{{item.currency}} {{+item.amount|number:'1.2-2'}}</td></tr>}</tbody></table></div>}@else{<p class="empty">No operating expenses in this range.</p>}</section>
 }
 <ng-template #ledger let-entries="entries">@if(entries.length){<div class="table-wrap"><table><thead><tr><th>Date</th><th>Professional</th><th>Description</th><th>Status</th><th>Amount</th></tr></thead><tbody>@for(item of entries;track item.entry_id){<tr><td>{{item.occurred_at|date:'mediumDate'}}</td><td>{{item.professional_display}}</td><td>{{item.description}}</td><td>{{item.status}}</td><td>{{item.currency}} {{+item.amount|number:'1.2-2'}}</td></tr>}</tbody></table></div>}@else{<p class="empty">No records in this range.</p>}</ng-template>
</app-admin-page-shell>`,styles:[`.filters{display:flex;gap:.5rem}.notice,.ledger,.expense-form{border:1px solid var(--app-border);border-radius:1rem;padding:1.1rem;background:var(--app-surface);margin-bottom:1rem}.notice h2,.expense-form h2,.ledger h2{margin:.1rem 0 .5rem}.notice p:last-child{color:var(--app-muted)}.money-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem;margin-bottom:1rem}.money-grid section{display:grid;gap:.4rem;border:1px solid var(--app-border);border-radius:.85rem;padding:1rem;background:var(--app-surface-soft)}.money-grid h3{margin:0;font-size:.8rem;color:var(--app-muted)}.money-grid strong{font-size:1.25rem}.form-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem;margin:1rem 0}.form-grid label{display:grid;gap:.3rem;font-size:.75rem;font-weight:700}.form-grid input,.form-grid select,.filters input,.filters select{min-height:2.5rem;border:1px solid var(--app-border);border-radius:.6rem;padding:.45rem;background:var(--app-surface);color:var(--app-text)}.wide{grid-column:span 2}.expense-form button{border:0;border-radius:.65rem;padding:.7rem 1rem;background:var(--app-primary);color:#fff;font-weight:800}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:.7rem;text-align:left;border-bottom:1px solid var(--app-border);white-space:nowrap}th{font-size:.7rem;color:var(--app-muted);text-transform:uppercase}.empty,.message{color:var(--app-muted)}@media(max-width:800px){.money-grid,.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}}`]})
export class AdminFinanceComponent implements OnInit{
 range='30d';startDate='';endDate='';summary?:AdminFinanceSummary;message='';canEdit=false;
 expense={amount:'',currency:'INR',category:'INFRASTRUCTURE',expense_date:new Date().toISOString().slice(0,10),vendor:'',description:''};
 constructor(private api:AdminPortalApiService){this.canEdit=api.hasPermission('admin.finance.edit')}
 ngOnInit():void{this.load()}
 load():void{if(this.range==='custom'&&(!this.startDate||!this.endDate))return;this.api.getFinance(this.range,this.startDate,this.endDate).subscribe({next:v=>{this.summary=v;this.message=''},error:e=>this.message=formatApiError(e,'Finance could not be loaded.')})}
 money(values:Record<string,string>):Array<{currency:string;amount:number}>{return Object.entries(values||{}).map(([currency,amount])=>({currency,amount:+amount}))}
 saveExpense():void{this.api.recordExpense(this.expense).subscribe({next:r=>{this.message=r.message;this.expense.amount='';this.expense.description='';this.load()},error:e=>this.message=formatApiError(e,'Expense could not be saved.')})}
}
