import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IonButton, IonContent, IonHeader, IonItem, IonLabel, IonList, IonRefresher, IonRefresherContent, IonTitle, IonToolbar } from '@ionic/angular/standalone';
import { TemplatesApiService, TrackingTemplateRecord } from '../../../core/api/templates-api.service';

@Component({ selector:'app-trainer-templates', standalone:true, imports:[RouterLink, IonButton, IonContent, IonHeader, IonItem, IonLabel, IonList, IonRefresher, IonRefresherContent, IonTitle, IonToolbar], template:`
<ion-header><ion-toolbar><ion-title>Templates</ion-title></ion-toolbar></ion-header><ion-content><ion-refresher slot="fixed" (ionRefresh)="refresh($event)"><ion-refresher-content /></ion-refresher><div class="page-pad">
<div class="kpi-grid"><div class="kpi-tile"><span>Templates Used</span><strong>{{templates.length}} / {{maxTemplates}}</strong></div><div class="kpi-tile"><span>Assigned Clients</span><strong>{{assignedTotal}}</strong></div></div>
<div class="section-head"><h2 class="section-title">Tracking Library</h2><ion-button size="small" routerLink="/trainer/tabs/manage">Create</ion-button></div>
<ion-list inset>@for(template of templates;track template.id){<ion-item><span class="accent" slot="start" [style.background]="template.accent || '#0b7de3'"></span><ion-label><h3>{{template.name}}</h3><p>{{template.cadence}} · {{template.fields.length}} fields · {{template.assigned_count || 0}} assigned</p><p>{{template.purpose}}</p></ion-label><ion-button slot="end" size="small" fill="clear" color="danger" (click)="remove(template.id)">Delete</ion-button></ion-item>}@empty{<ion-item lines="none"><ion-label color="medium">No templates yet. Use Manage to create one.</ion-label></ion-item>}</ion-list>
@if(message){<p class="error-text">{{message}}</p>}</div></ion-content>`,styles:[`.accent{width:.55rem;height:2.8rem;border-radius:1rem}`]})
export class TrainerTemplatesPage implements OnInit { private readonly api=inject(TemplatesApiService); templates:TrackingTemplateRecord[]=[]; maxTemplates=0; message=''; get assignedTotal():number{return this.templates.reduce((sum,item)=>sum+Number(item.assigned_count||0),0)} ngOnInit():void{this.load()} refresh(event:CustomEvent):void{this.load(()=>(event.target as HTMLIonRefresherElement).complete())} remove(id:number):void{this.api.deleteTemplate(id).subscribe({next:()=>this.load(),error:()=>this.message='Template could not be deleted.'})} private load(done?:()=>void):void{this.api.getTemplates().subscribe({next:r=>{this.templates=r.templates;this.maxTemplates=r.max_templates;this.message='';done?.()},error:()=>{this.message='Could not load templates.';done?.()}})} }
