import { DatePipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { IonButton, IonContent, IonHeader, IonItem, IonLabel, IonList, IonRefresher, IonRefresherContent, IonTitle, IonToolbar } from '@ionic/angular/standalone';
import { ClientApiService, ClientDashboardResponse, ClientMeResponse } from '../../../core/api/client-api.service';

@Component({ selector:'app-client-dashboard-mobile', standalone:true, imports:[DatePipe, RouterLink, IonButton, IonContent, IonHeader, IonItem, IonLabel, IonList, IonRefresher, IonRefresherContent, IonTitle, IonToolbar], template:`
<ion-header><ion-toolbar><ion-title>Dashboard</ion-title></ion-toolbar></ion-header><ion-content><ion-refresher slot="fixed" (ionRefresh)="refresh($event)"><ion-refresher-content /></ion-refresher><div class="page-pad">
@if(me){<p class="eyebrow">Good morning</p><h1 class="welcome">{{me.client.first_name || 'Welcome'}}! 👋</h1>} @else {<h1 class="welcome">Your plan</h1>}
@if(data;as d){
<div class="plan-card"><div><strong>Today's plan</strong><span>{{d.summary.completed_schedules_last_30}} completed this month</span></div><strong class="plan-progress">{{d.summary.consistency_percent}}%</strong></div>
<h2 class="section-title">Today's checklist</h2><ion-list inset>@for(item of d.schedules;track item.id){<ion-item><ion-label><h3>{{item.title}}</h3><p>{{item.date|date:'mediumDate'}} {{item.time||''}}</p></ion-label><span class="check-dot" [class.done]="item.status !== 'pending'">{{item.status !== 'pending' ? '✓' : ''}}</span></ion-item>}@empty{<ion-item lines="none"><ion-label color="medium">No scheduled tasks today.</ion-label></ion-item>}</ion-list>
<h2 class="section-title">Progress overview</h2><div class="kpi-grid"><div class="kpi-tile"><span>Current streak</span><strong>{{d.summary.current_streak}} days</strong></div><div class="kpi-tile"><span>Consistency</span><strong>{{d.summary.consistency_percent}}%</strong><small>{{d.summary.active_days_last_30}} active days</small></div><div class="kpi-tile"><span>Check-ins</span><strong>{{d.summary.entries_last_30_days}}</strong></div><div class="kpi-tile"><span>Programs</span><strong>{{d.summary.active_templates}}</strong></div></div><ion-button expand="block" routerLink="/client/tabs/templates">Record a check-in</ion-button>
}@if(message){<p class="error-text">{{message}}</p>}</div></ion-content>`, styles:[`.welcome{margin:.2rem 0 1rem;font-size:1.5rem}.plan-card{display:flex;align-items:center;justify-content:space-between;padding:1rem;border-radius:1.1rem;background:linear-gradient(135deg,#e9f4ff,#eefbf5);border:1px solid var(--app-border)}.plan-card span{display:block;margin-top:.3rem;color:var(--app-muted);font-size:.75rem}.plan-progress{font-size:1.4rem;color:var(--ion-color-primary)}.check-dot{display:grid;place-items:center;width:1.6rem;height:1.6rem;border-radius:50%;border:2px solid var(--app-border);color:#fff;font-weight:800}.check-dot.done{border-color:var(--ion-color-success);background:var(--ion-color-success)}`]})
export class ClientDashboardPage implements OnInit{private readonly api=inject(ClientApiService);data:ClientDashboardResponse|null=null;me:ClientMeResponse|null=null;message='';ngOnInit():void{this.load()}refresh(event:CustomEvent):void{this.load(()=>(event.target as HTMLIonRefresherElement).complete())}private load(done?:()=>void):void{this.api.getMe().subscribe({next:value=>this.me=value,error:()=>this.me=null});this.api.getDashboard().subscribe({next:value=>{this.data=value;this.message='';done?.()},error:()=>{this.message='Could not load dashboard.';done?.()}})}}
