import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { IonButton, IonContent, IonHeader, IonInput, IonItem, IonLabel, IonList, IonListHeader, IonTextarea, IonTitle, IonToolbar } from '@ionic/angular/standalone';
import { ClientAccountRequest, ClientApiService, ClientMeResponse } from '../../../core/api/client-api.service';
import { MobileSupportIncidentsPage } from '../../shared/support-incidents.page';

@Component({selector:'app-client-settings-mobile',standalone:true,imports:[FormsModule,IonButton,IonContent,IonHeader,IonInput,IonItem,IonLabel,IonList,IonListHeader,IonTextarea,IonTitle,IonToolbar,MobileSupportIncidentsPage],template:`
<ion-header><ion-toolbar><ion-title>Settings</ion-title></ion-toolbar></ion-header><ion-content><div class="page-pad">
@if(me;as data){<ion-list inset><ion-list-header><ion-label>My Account</ion-label></ion-list-header><ion-item><ion-label><p>Name</p><h3>{{data.client.first_name}} {{data.client.last_name}}</h3></ion-label></ion-item><ion-item><ion-label><p>Email</p><h3>{{data.client.email}}</h3></ion-label></ion-item><ion-item><ion-label><p>Group</p><h3>{{data.client.group_name}}</h3></ion-label></ion-item></ion-list>}
<ion-list inset><ion-list-header><ion-label>Security</ion-label></ion-list-header><ion-item><ion-input label="Current password" labelPlacement="stacked" type="password" [(ngModel)]="currentPassword" name="currentPassword" /></ion-item><ion-item><ion-input label="New password" labelPlacement="stacked" type="password" [(ngModel)]="password" name="password" /></ion-item><ion-item><ion-input label="Confirm password" labelPlacement="stacked" type="password" [(ngModel)]="confirmPassword" name="confirmPassword" /></ion-item></ion-list><ion-button expand="block" (click)="changePassword()">Change Password</ion-button>
<ion-list inset><ion-list-header><ion-label>Privacy & Legal</ion-label></ion-list-header><ion-item><ion-label class="ion-text-wrap"><h3>Terms & Conditions</h3><p>Use CoachFlow respectfully, keep credentials private, and provide accurate check-in information.</p></ion-label></ion-item><ion-item><ion-label class="ion-text-wrap"><h3>Privacy Policy</h3><p>Your profile, coaching history, messages, and check-ins are visible to your assigned trainer and protected as account data.</p></ion-label></ion-item></ion-list>
<ion-list inset class="danger-list"><ion-list-header><ion-label color="danger">Delete Account</ion-label></ion-list-header>@if(deletionRequest?.status==='pending'){<ion-item><ion-label class="ion-text-wrap"><h3>Awaiting trainer review</h3><p>Your request is in the trainer action queue.</p></ion-label></ion-item><ion-button expand="block" fill="outline" color="danger" (click)="withdrawDeletion()">Withdraw Request</ion-button>}@else{<ion-item><ion-textarea label="Reason (optional)" labelPlacement="stacked" rows="3" [(ngModel)]="deletionNote" name="deletionNote" /></ion-item><ion-button expand="block" color="danger" (click)="requestDeletion()">Request Account Deletion</ion-button>}</ion-list>
<app-mobile-support-incidents role="client" /><ion-button expand="block" fill="clear" (click)="logout()">Sign Out</ion-button>@if(message){<p [class]="messageType==='error'?'error-text':'empty-note'">{{message}}</p>}</div></ion-content>`})
export class ClientSettingsPage implements OnInit{private readonly api=inject(ClientApiService);private readonly router=inject(Router);me:ClientMeResponse|null=null;deletionRequest:ClientAccountRequest|null=null;deletionNote='';currentPassword='';password='';confirmPassword='';message='';messageType:'success'|'error'='success';ngOnInit():void{this.api.getMe().subscribe({next:value=>this.me=value});this.api.getAccountDeletionRequest().subscribe({next:r=>this.deletionRequest=r.deletion_request})}changePassword():void{if(!this.currentPassword||!this.password||this.password!==this.confirmPassword){this.messageType='error';this.message='Complete all fields and make sure new passwords match.';return}this.api.changePassword(this.currentPassword,this.password,this.confirmPassword).subscribe({next:r=>{this.api.clearSession();this.message=r.message;void this.router.navigateByUrl('/client/login',{replaceUrl:true})},error:()=>{this.messageType='error';this.message='Password could not be changed.'}})}requestDeletion():void{this.api.requestAccountDeletion(this.deletionNote.trim()).subscribe({next:r=>{this.deletionRequest=r.deletion_request;this.messageType='success';this.message=r.message},error:()=>{this.messageType='error';this.message='Deletion request could not be sent.'}})}withdrawDeletion():void{this.api.withdrawAccountDeletionRequest().subscribe({next:r=>{this.deletionRequest=null;this.message=r.message},error:()=>{this.messageType='error';this.message='Request could not be withdrawn.'}})}logout():void{this.api.logout().subscribe({next:()=>this.finish(),error:()=>this.finish()})}private finish():void{this.api.clearSession();void this.router.navigateByUrl('/',{replaceUrl:true})}}
