# Generated by Django 5.2.16 on 2026-07-18 17:01

import admin_portal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('section', models.CharField(db_index=True, max_length=60)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'admin_permissions',
                'ordering': ['section', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='admin_portal.adminpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='admin_portal.adminrole')),
            ],
            options={
                'db_table': 'admin_role_permissions',
            },
        ),
        migrations.AddField(
            model_name='adminrole',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='admin_portal.AdminRolePermission', to='admin_portal.adminpermission'),
        ),
        migrations.CreateModel(
            name='AdminStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, default=admin_portal.models.staff_reference, editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_staff_profiles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='admin_portal.adminrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='AdminStaffPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_overrides', to='admin_portal.adminpermission')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='admin_portal.adminstaffprofile')),
            ],
            options={
                'db_table': 'admin_staff_permission_overrides',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_reference_snapshot', models.CharField(blank=True, max_length=120)),
                ('role_snapshot', models.CharField(blank=True, max_length=80)),
                ('permission_used', models.CharField(blank=True, db_index=True, max_length=100)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('target_display', models.CharField(blank=True, db_index=True, max_length=180)),
                ('professional_username_snapshot', models.CharField(blank=True, max_length=150)),
                ('professional_reference_snapshot', models.CharField(blank=True, max_length=24)),
                ('client_reference_snapshot', models.CharField(blank=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('correlation_id', models.CharField(db_index=True, max_length=40)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='admin_portal.adminstaffprofile')),
            ],
            options={
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(db_index=True, default=admin_portal.models.error_log_reference, editable=False, max_length=24, unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=12)),
                ('source', models.CharField(choices=[('client_app', 'Client app'), ('backend', 'Backend')], db_index=True, default='client_app', max_length=12)),
                ('level', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('fatal', 'Fatal')], db_index=True, default='error', max_length=10)),
                ('reporter_role', models.CharField(blank=True, choices=[('professional', 'Professional'), ('client', 'Client')], db_index=True, max_length=12)),
                ('professional_username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('client_username', models.CharField(blank=True, max_length=150)),
                ('client_reference', models.CharField(blank=True, max_length=32)),
                ('message', models.CharField(max_length=500)),
                ('stack_trace', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('device_info', models.CharField(blank=True, max_length=300)),
                ('request_path', models.CharField(blank=True, max_length=300)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=14)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reporter_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='accounts.clientaccess')),
                ('reporter_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'error_logs',
                'ordering': ['professional_username', '-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(db_index=True, default=admin_portal.models.finance_reference, editable=False, max_length=24, unique=True)),
                ('entry_type', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_ledger_entries',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='adminrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_admin_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='adminstaffpermissionoverride',
            constraint=models.UniqueConstraint(fields=('staff', 'permission'), name='unique_admin_staff_override'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['target_type', 'target_display'], name='admin_audit_target_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['platform', 'status'], name='error_platform_status_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['professional_username'], name='error_prof_username_idx'),
        ),
    ]
