from django.urls import path

from .views import (
  ClientAccessCreateView,
  ClientAccessDeleteView,
  ClientAccessDetailView,
  ClientAccessPasswordResetView,
  ClientAccessPhotoView,
  ClientAccessResetView,
  ClientAccessStatusView,
  ClientAdditionalInfoView,
  ClientChatView,
  ClientDetailChangeRequestView,
  ClientAccountDeletionRequestView,
  ClientDashboardView,
  ClientMeView,
  ClientPhotoView,
  ClientProgressListView,
  ClientProgressDetailView,
  ClientReminderListView,
  ClientReminderDetailView,
  ClientTrackingEntryDetailView,
  ClientPasswordChangeView,
  ClientPortalProgressView,
  ClientTemplateAssignmentDetailView,
  ClientTemplateAssignmentListView,
  ClientTemplateListView,
  ClientTrackingEntryListView,
  ClientTrackingEntryView,
  ClientTrainerNotesView,
  ClientSupportIncidentDetailView,
  ClientSupportIncidentListView,
  GroupClientAccessListView,
  ClientLoginView,
  ClientLogoutView,
  ClientTrainerLookupView,
  ClientRegistrationFormView,
  ManualClientAccessCreateView,
  PublicGroupRegistrationView,
  EmailAvailabilityView,
  EmailOtpRequestView,
  EmailOtpVerifyView,
  FormsGroupsOverviewView,
  PendingLeadSubmissionView,
  PasswordResetConfirmView,
  PasswordResetOtpRequestView,
  PasswordResetOtpVerifyView,
  PublicLeadFormView,
  StandardTemplateAdoptView,
  StandardTemplateListView,
  TrackingTemplateDetailView,
  TrackingTemplateListView,
  TrainerAccountView,
  TrainerClientChangeRequestActionView,
  TrainerClientChatView,
  TrainerUpcomingRemindersView,
  TrainerCodeAvailabilityView,
  TrainerCodeUpdateView,
  TrainerDataUsageView,
  TrainerDirectoryView,
  TrainerGroupListView,
  TrainerGroupDetailView,
  TrainerLeadFormView,
  TrainerLoginView,
  TrainerLogoutView,
  TrainerPasswordChangeView,
  TrainerProfileStatusView,
  TrainerProfileView,
  TrainerProfileVisibilityView,
  TrainerReferenceCategoryDetailView,
  TrainerReferenceCategoryListView,
  TrainerReferenceDetailView,
  TrainerReferenceListView,
  TrainerSignupView,
  TrainerSupportIncidentDetailView,
  TrainerSupportIncidentListView,
  TrainerTrackingEntryDetailView,
  UsernameAvailabilityView,
)

urlpatterns = [
  path('trainer/check-email/', EmailAvailabilityView.as_view(), name='trainer-check-email'),
  path('trainer/request-email-otp/', EmailOtpRequestView.as_view(), name='trainer-request-email-otp'),
  path('trainer/verify-email-otp/', EmailOtpVerifyView.as_view(), name='trainer-verify-email-otp'),
  path('trainer/check-username/', UsernameAvailabilityView.as_view(), name='trainer-check-username'),
  path('trainer/check-trainer-code/', TrainerCodeAvailabilityView.as_view(), name='trainer-check-code'),
  path('trainer/account/trainer-code/', TrainerCodeUpdateView.as_view(), name='trainer-code-update'),
  path('trainer/signup/', TrainerSignupView.as_view(), name='trainer-signup'),
  path('trainer/login/', TrainerLoginView.as_view(), name='trainer-login'),
  path('client/trainer-lookup/', ClientTrainerLookupView.as_view(), name='client-trainer-lookup'),
  path('client/trainer-directory/', TrainerDirectoryView.as_view(), name='client-trainer-directory'),
  path('client/login/', ClientLoginView.as_view(), name='client-login'),
  path('client/logout/', ClientLogoutView.as_view(), name='client-logout'),
  path('trainer/logout/', TrainerLogoutView.as_view(), name='trainer-logout'),
  path('trainer/account/', TrainerAccountView.as_view(), name='trainer-account'),
  path('trainer/account/change-password/', TrainerPasswordChangeView.as_view(), name='trainer-change-password'),
  path('trainer/profile/status/', TrainerProfileStatusView.as_view(), name='trainer-profile-status'),
  path('trainer/data-usage/', TrainerDataUsageView.as_view(), name='trainer-data-usage'),
  path('trainer/support/incidents/', TrainerSupportIncidentListView.as_view(), name='trainer-support-incidents'),
  path('trainer/support/incidents/<str:incident_id>/', TrainerSupportIncidentDetailView.as_view(), name='trainer-support-incident-detail'),
  path('trainer/profile/', TrainerProfileView.as_view(), name='trainer-profile'),
  path('trainer/profile/visibility/', TrainerProfileVisibilityView.as_view(), name='trainer-profile-visibility'),
  path('trainer/forms-groups/', FormsGroupsOverviewView.as_view(), name='trainer-forms-groups'),
  path('trainer/forms-groups/lead-form/', TrainerLeadFormView.as_view(), name='trainer-lead-form'),
  path('trainer/forms-groups/groups/', TrainerGroupListView.as_view(), name='trainer-groups'),
  path('trainer/forms-groups/groups/<int:group_id>/', TrainerGroupDetailView.as_view(), name='trainer-group-detail'),
  path('trainer/forms-groups/groups/<int:group_id>/registration-form/', ClientRegistrationFormView.as_view(), name='trainer-group-registration-form'),
  path('trainer/forms-groups/groups/<int:group_id>/clients/', GroupClientAccessListView.as_view(), name='trainer-group-clients'),
  path('trainer/forms-groups/clients/manual/', ManualClientAccessCreateView.as_view(), name='trainer-manual-client-create'),
  path('trainer/forms-groups/clients/<int:client_id>/', ClientAccessDetailView.as_view(), name='trainer-client-detail'),
  path('trainer/forms-groups/clients/<int:client_id>/reset-password/', ClientAccessPasswordResetView.as_view(), name='trainer-client-reset-password'),
  path('trainer/forms-groups/clients/<int:client_id>/status/', ClientAccessStatusView.as_view(), name='trainer-client-status'),
  path('trainer/forms-groups/clients/<int:client_id>/reset/', ClientAccessResetView.as_view(), name='trainer-client-reset'),
  path('trainer/forms-groups/clients/<int:client_id>/delete/', ClientAccessDeleteView.as_view(), name='trainer-client-delete'),
  path('trainer/forms-groups/clients/<int:client_id>/photo/', ClientAccessPhotoView.as_view(), name='trainer-client-photo'),
  path('trainer/forms-groups/clients/<int:client_id>/additional-info/', ClientAdditionalInfoView.as_view(), name='trainer-client-additional-info'),
  path('trainer/forms-groups/clients/<int:client_id>/reminders/', ClientReminderListView.as_view(), name='trainer-client-reminders'),
  path('trainer/reminders/<int:reminder_id>/', ClientReminderDetailView.as_view(), name='trainer-reminder-detail'),
  path('trainer/reminders/upcoming/', TrainerUpcomingRemindersView.as_view(), name='trainer-reminders-upcoming'),
  path('trainer/forms-groups/clients/<int:client_id>/progress/', ClientProgressListView.as_view(), name='trainer-client-progress'),
  path('trainer/progress/<int:entry_id>/', ClientProgressDetailView.as_view(), name='trainer-progress-detail'),
  path('trainer/forms-groups/pending/<int:submission_id>/', PendingLeadSubmissionView.as_view(), name='trainer-pending-form'),
  path('trainer/forms-groups/pending/<int:submission_id>/create-client-access/', ClientAccessCreateView.as_view(), name='trainer-create-client-access'),
  path('public/forms/<slug:public_slug>/', PublicLeadFormView.as_view(), name='public-lead-form'),
  path('public/group-registration/<slug:public_slug>/', PublicGroupRegistrationView.as_view(), name='public-group-registration'),
  path('trainer/password-reset/request-otp/', PasswordResetOtpRequestView.as_view(), name='trainer-password-reset-request-otp'),
  path('trainer/password-reset/verify-otp/', PasswordResetOtpVerifyView.as_view(), name='trainer-password-reset-verify-otp'),
  path('trainer/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='trainer-password-reset-confirm'),
  path('trainer/references/categories/', TrainerReferenceCategoryListView.as_view(), name='trainer-reference-categories'),
  path('trainer/references/categories/<int:category_id>/', TrainerReferenceCategoryDetailView.as_view(), name='trainer-reference-category-detail'),
  path('trainer/references/', TrainerReferenceListView.as_view(), name='trainer-references'),
  path('trainer/references/<int:reference_id>/', TrainerReferenceDetailView.as_view(), name='trainer-reference-detail'),
  path('trainer/templates/standard/', StandardTemplateListView.as_view(), name='trainer-standard-templates'),
  path('trainer/templates/adopt-standard/', StandardTemplateAdoptView.as_view(), name='trainer-adopt-standard-template'),
  path('trainer/templates/', TrackingTemplateListView.as_view(), name='trainer-templates'),
  path('trainer/templates/<int:template_id>/', TrackingTemplateDetailView.as_view(), name='trainer-template-detail'),
  path('trainer/forms-groups/clients/<int:client_id>/assignments/', ClientTemplateAssignmentListView.as_view(), name='trainer-client-assignments'),
  path('trainer/forms-groups/clients/<int:client_id>/assignments/<int:assignment_id>/', ClientTemplateAssignmentDetailView.as_view(), name='trainer-client-assignment-detail'),
  path('trainer/forms-groups/clients/<int:client_id>/entries/', ClientTrackingEntryListView.as_view(), name='trainer-client-entries'),
  path('trainer/forms-groups/clients/<int:client_id>/notes/', ClientTrainerNotesView.as_view(), name='trainer-client-notes'),
  path('trainer/forms-groups/clients/<int:client_id>/change-requests/<int:request_id>/', TrainerClientChangeRequestActionView.as_view(), name='trainer-client-change-request-action'),
  path('trainer/entries/<int:entry_id>/', TrainerTrackingEntryDetailView.as_view(), name='trainer-entry-detail'),
  path('trainer/clients/<int:client_id>/chat/', TrainerClientChatView.as_view(), name='trainer-client-chat'),
  path('client/change-password/', ClientPasswordChangeView.as_view(), name='client-change-password'),
  path('client/dashboard/', ClientDashboardView.as_view(), name='client-dashboard'),
  path('client/me/', ClientMeView.as_view(), name='client-me'),
  path('client/photo/', ClientPhotoView.as_view(), name='client-photo'),
  path('client/detail-change-request/', ClientDetailChangeRequestView.as_view(), name='client-detail-change-request'),
  path('client/account-deletion-request/', ClientAccountDeletionRequestView.as_view(), name='client-account-deletion-request'),
  path('client/templates/', ClientTemplateListView.as_view(), name='client-templates'),
  path('client/entries/', ClientTrackingEntryView.as_view(), name='client-entries'),
  path('client/entries/<int:entry_id>/', ClientTrackingEntryDetailView.as_view(), name='client-entry-detail'),
  path('client/progress/', ClientPortalProgressView.as_view(), name='client-progress'),
  path('client/chat/', ClientChatView.as_view(), name='client-chat'),
  path('client/support/incidents/', ClientSupportIncidentListView.as_view(), name='client-support-incidents'),
  path('client/support/incidents/<str:incident_id>/', ClientSupportIncidentDetailView.as_view(), name='client-support-incident-detail'),
]
