from django.urls import path

from .views_notifications import (
  ClientNotificationPreferencesView, ClientNotificationsView,
  ProfessionalNotificationPreferencesView, ProfessionalNotificationsView,
)

from .group_import import GroupImportConfirmView, GroupImportPreviewView

from .views import (
  ClientAccessCreateView,
  ClientAccessDeleteView,
  ClientAccessDetailView,
  ClientAccessGrantPortalAccessView,
  ClientAccessRevokePortalAccessView,
  ClientAccessPasswordResetView,
  ClientAccessPhotoView,
  ClientAccessResetView,
  ClientAccessExportView,
  ClientAccessStatusView,
  ClientAdditionalInfoView,
  ClientChatView,
  ClientChatUnreadView,
  ClientDetailChangeRequestView,
  ClientAccountDeletionRequestView,
  ClientDashboardView,
  ClientMeView,
  ClientPhotoView,
  ClientProgressListView,
  ClientProgressDetailView,
  ClientReminderListView,
  ClientReminderDetailView,
  ClientTrackingEntryDetailView,
  ClientPasswordChangeView,
  ClientPortalProgressView,
  ClientTemplateAssignmentDetailView,
  ClientTemplateAssignmentListView,
  ClientTemplateListView,
  ClientTrackingEntryListView,
  ClientTrackingEntryView,
  ClientProfessionalNotesView,
  ClientSupportIncidentDetailView,
  ClientSupportIncidentListView,
  ErrorReportView,
  GroupClientAccessListView,
  ClientLoginView,
  ClientLogoutView,
  ClientProfessionalLookupView,
  ClientRegistrationFormView,
  ManualClientAccessCreateView,
  PublicGroupRegistrationView,
  EmailAvailabilityView,
  EmailOtpRequestView,
  EmailOtpVerifyView,
  FormsGroupsOverviewView,
  PendingLeadSubmissionView,
  PasswordResetConfirmView,
  PasswordResetOtpRequestView,
  PasswordResetOtpVerifyView,
  PublicLeadFormView,
  StandardTemplateAdoptView,
  StandardTemplateListView,
  stripe_webhook,
  razorpay_webhook,
  TrackingTemplateDetailView,
  TrackingTemplateListView,
  ProfessionalAccountView,
  ProfessionalBillingCancelView,
  ProfessionalBillingCheckoutView,
  ProfessionalBillingPortalView,
  ProfessionalBillingStatusView,
  ProfessionalClientChangeRequestActionView,
  ProfessionalClientChatView,
  ProfessionalChatUnreadView,
  ProfessionalUpcomingRemindersView,
  ProfessionalCodeAvailabilityView,
  ProfessionalCodeUpdateView,
  ProfessionalDataUsageView,
  ProfessionalOnboardingStatusView,
  ProfessionalMeetingEligibilityView,
  RecycleBinListView,
  RecycleBinPermanentDeleteView,
  RecycleBinRestoreView,
  ProfessionalDirectoryView,
  ProfessionalGroupListView,
  ProfessionalGroupDetailView,
  ProfessionalLeadFormView,
  ProfessionalLeadFormStatusView,
  ProfessionalLoginView,
  ProfessionalLogoutView,
  ProfessionalPasswordChangeView,
  ProfessionalProfileStatusView,
  ProfessionalProfileView,
  ProfessionalProfileVisibilityView,
  ProfessionalReferenceCategoryDetailView,
  ProfessionalReferenceCategoryListView,
  ProfessionalReferenceDetailView,
  ProfessionalReferenceListView,
  ProfessionalSignupView,
  ProfessionalSupportIncidentDetailView,
  ProfessionalSupportIncidentListView,
  ProfessionalTrackingEntryDetailView,
  UsernameAvailabilityView,
)
from .views_payments import (
  ClientPaymentMethodAccessView,
  ClientPaymentNotificationsView,
  ClientPaymentProofFileView,
  ClientPaymentRequestDetailView,
  ClientPaymentRequestListView,
  ManualPaymentProfileDetailView,
  ManualPaymentProfileListView,
  ManualPaymentProfilePreviewView,
  PaymentProofAcknowledgeView,
  PaymentProofFileView,
  PaymentProofRejectView,
  PaymentProofRequestInfoView,
  PaymentProofSubmitView,
  PaymentReconciliationView,
  PaymentRequestCancelView,
  PaymentRequestDetailView,
  PaymentRequestListView,
  ClientPaymentConfirmationView,
  ClientPaymentRecordListView,
  PaymentConfirmationView,
  PaymentRecordDetailView,
  PaymentRecordListView,
  PaymentReportingEstimateView,
  ProfessionalRevenueSummaryView,
  ProfessionalPaymentActionsView,
  ProfessionalPaymentNotificationsView,
  ProfessionalPaymentSettingsView,
  ProfessionalTransactionLedgerView,
)
from .views_scheduling import (
  ClientMeetingCalendarInviteView,
  ClientMeetingRespondView,
  ClientScheduledMeetingListView,
  ProfessionalAvailabilityWindowDetailView,
  ProfessionalAvailabilityWindowsView,
  ProfessionalSchedulingSettingsView,
  ProfessionalSchedulingSlotsView,
  ScheduledMeetingCancelView,
  ScheduledMeetingListView,
  ScheduledMeetingRescheduleView,
  ProfessionalLeadMeetingSettingsView,
  PublicLeadMeetingSlotsView,
  PublicLeadMeetingRequestView,
  ProfessionalLeadMeetingRequestListView,
  ProfessionalLeadMeetingRequestActionView,
)

urlpatterns = [
  path('professional/notifications/', ProfessionalNotificationsView.as_view(), name='professional-notifications'),
  path('professional/notification-preferences/', ProfessionalNotificationPreferencesView.as_view(), name='professional-notification-preferences'),
  path('client/notifications/', ClientNotificationsView.as_view(), name='client-notifications'),
  path('client/notification-preferences/', ClientNotificationPreferencesView.as_view(), name='client-notification-preferences'),
  path('professional/check-email/', EmailAvailabilityView.as_view(), name='professional-check-email'),
  path('professional/request-email-otp/', EmailOtpRequestView.as_view(), name='professional-request-email-otp'),
  path('professional/verify-email-otp/', EmailOtpVerifyView.as_view(), name='professional-verify-email-otp'),
  path('professional/check-username/', UsernameAvailabilityView.as_view(), name='professional-check-username'),
  path('professional/check-professional-code/', ProfessionalCodeAvailabilityView.as_view(), name='professional-check-code'),
  path('professional/account/professional-code/', ProfessionalCodeUpdateView.as_view(), name='professional-code-update'),
  path('professional/signup/', ProfessionalSignupView.as_view(), name='professional-signup'),
  path('professional/login/', ProfessionalLoginView.as_view(), name='professional-login'),
  path('client/professional-lookup/', ClientProfessionalLookupView.as_view(), name='client-professional-lookup'),
  path('client/professional-directory/', ProfessionalDirectoryView.as_view(), name='client-professional-directory'),
  path('client/login/', ClientLoginView.as_view(), name='client-login'),
  path('client/logout/', ClientLogoutView.as_view(), name='client-logout'),
  path('professional/logout/', ProfessionalLogoutView.as_view(), name='professional-logout'),
  path('professional/account/', ProfessionalAccountView.as_view(), name='professional-account'),
  path('professional/account/change-password/', ProfessionalPasswordChangeView.as_view(), name='professional-change-password'),
  path('professional/profile/status/', ProfessionalProfileStatusView.as_view(), name='professional-profile-status'),
  path('professional/data-usage/', ProfessionalDataUsageView.as_view(), name='professional-data-usage'),
  path('professional/recycle-bin/', RecycleBinListView.as_view(), name='professional-recycle-bin'),
  path('professional/recycle-bin/<int:item_id>/restore/', RecycleBinRestoreView.as_view(), name='professional-recycle-bin-restore'),
  path('professional/recycle-bin/<int:item_id>/', RecycleBinPermanentDeleteView.as_view(), name='professional-recycle-bin-delete'),
  path('professional/billing/status/', ProfessionalBillingStatusView.as_view(), name='professional-billing-status'),
  path('professional/dashboard/onboarding-status/', ProfessionalOnboardingStatusView.as_view(), name='professional-onboarding-status'),
  path('professional/meetings/eligibility/', ProfessionalMeetingEligibilityView.as_view(), name='professional-meeting-eligibility'),
  path('professional/billing/checkout/', ProfessionalBillingCheckoutView.as_view(), name='professional-billing-checkout'),
  path('professional/billing/cancel/', ProfessionalBillingCancelView.as_view(), name='professional-billing-cancel'),
  path('professional/billing/portal/', ProfessionalBillingPortalView.as_view(), name='professional-billing-portal'),
  path('billing/webhook/', stripe_webhook, name='stripe-webhook'),
  path('billing/razorpay/webhook/', razorpay_webhook, name='razorpay-webhook'),
  # --- Client Payments (professional collecting from clients) ---
  path('professional/payments/settings/', ProfessionalPaymentSettingsView.as_view(), name='professional-payment-settings'),
  path('professional/payments/transactions/', ProfessionalTransactionLedgerView.as_view(), name='professional-payment-transactions'),
  path('professional/payments/methods/', ManualPaymentProfileListView.as_view(), name='professional-payment-methods'),
  path('professional/payments/methods/<int:method_id>/', ManualPaymentProfileDetailView.as_view(), name='professional-payment-method-detail'),
  path('professional/payments/methods/<int:method_id>/preview/', ManualPaymentProfilePreviewView.as_view(), name='professional-payment-method-preview'),
  path('professional/payments/clients/<int:client_id>/methods/', ClientPaymentMethodAccessView.as_view(), name='professional-client-payment-methods'),
  path('professional/payments/clients/<int:client_id>/requests/', PaymentRequestListView.as_view(), name='professional-client-payment-requests'),
  path('professional/payments/requests/<str:request_id>/', PaymentRequestDetailView.as_view(), name='professional-payment-request-detail'),
  path('professional/payments/requests/<str:request_id>/cancel/', PaymentRequestCancelView.as_view(), name='professional-payment-request-cancel'),
  path('professional/payments/notifications/', ProfessionalPaymentNotificationsView.as_view(), name='professional-payment-notifications'),
  path('professional/payments/actions/', ProfessionalPaymentActionsView.as_view(), name='professional-payment-actions'),
  path('professional/payments/records/', PaymentRecordListView.as_view(), name='professional-payment-records'),
  path('professional/payments/records/<str:record_id>/', PaymentRecordDetailView.as_view(), name='professional-payment-record-detail'),
  path('professional/payments/reporting-estimate/', PaymentReportingEstimateView.as_view(), name='professional-payment-reporting-estimate'),
  path('professional/payments/revenue-summary/', ProfessionalRevenueSummaryView.as_view(), name='professional-payments-revenue-summary'),
  path('professional/payments/records/<str:record_id>/confirmation/', PaymentConfirmationView.as_view(), name='professional-payment-confirmation'),
  path('professional/payments/proofs/<int:proof_id>/acknowledge/', PaymentProofAcknowledgeView.as_view(), name='professional-payment-proof-acknowledge'),
  path('professional/payments/proofs/<int:proof_id>/reject/', PaymentProofRejectView.as_view(), name='professional-payment-proof-reject'),
  path('professional/payments/proofs/<int:proof_id>/request-info/', PaymentProofRequestInfoView.as_view(), name='professional-payment-proof-request-info'),
  path('professional/payments/proofs/<int:proof_id>/file/', PaymentProofFileView.as_view(), name='professional-payment-proof-file'),
  path('professional/payments/reconciliation/', PaymentReconciliationView.as_view(), name='professional-payment-reconciliation'),
  path('client/payments/records/', ClientPaymentRecordListView.as_view(), name='client-payment-records'),
  path('client/payments/records/<str:record_id>/confirmation/', ClientPaymentConfirmationView.as_view(), name='client-payment-confirmation'),
  path('client/payments/requests/', ClientPaymentRequestListView.as_view(), name='client-payment-requests'),
  path('client/payments/requests/<str:request_id>/', ClientPaymentRequestDetailView.as_view(), name='client-payment-request-detail'),
  path('client/payments/requests/<str:request_id>/proof/', PaymentProofSubmitView.as_view(), name='client-payment-proof-submit'),
  path('client/payments/proofs/<int:proof_id>/file/', ClientPaymentProofFileView.as_view(), name='client-payment-proof-file'),
  path('client/payments/notifications/', ClientPaymentNotificationsView.as_view(), name='client-payment-notifications'),
  path('professional/scheduling/settings/', ProfessionalSchedulingSettingsView.as_view(), name='professional-scheduling-settings'),
  path('professional/forms-groups/lead-form/meeting-settings/', ProfessionalLeadMeetingSettingsView.as_view(), name='professional-lead-meeting-settings'),
  path('professional/lead-meeting-requests/', ProfessionalLeadMeetingRequestListView.as_view(), name='professional-lead-meeting-requests'),
  path('professional/lead-meeting-requests/<int:request_id>/action/', ProfessionalLeadMeetingRequestActionView.as_view(), name='professional-lead-meeting-request-action'),
  path('professional/scheduling/availability-windows/', ProfessionalAvailabilityWindowsView.as_view(), name='professional-scheduling-availability-windows'),
  path('professional/scheduling/availability-windows/<int:window_id>/', ProfessionalAvailabilityWindowDetailView.as_view(), name='professional-scheduling-availability-window-detail'),
  path('professional/scheduling/slots/', ProfessionalSchedulingSlotsView.as_view(), name='professional-scheduling-slots'),
  path('professional/scheduling/meetings/', ScheduledMeetingListView.as_view(), name='professional-scheduling-meetings'),
  path('professional/scheduling/meetings/<int:meeting_id>/reschedule/', ScheduledMeetingRescheduleView.as_view(), name='professional-scheduling-meeting-reschedule'),
  path('professional/scheduling/meetings/<int:meeting_id>/cancel/', ScheduledMeetingCancelView.as_view(), name='professional-scheduling-meeting-cancel'),
  path('client/scheduling/meetings/', ClientScheduledMeetingListView.as_view(), name='client-scheduling-meetings'),
  path('client/scheduling/meetings/<int:meeting_id>/calendar/', ClientMeetingCalendarInviteView.as_view(), name='client-scheduling-meeting-calendar'),
  path('client/scheduling/meetings/<int:meeting_id>/respond/', ClientMeetingRespondView.as_view(), name='client-scheduling-meeting-respond'),
  path('professional/support/incidents/', ProfessionalSupportIncidentListView.as_view(), name='professional-support-incidents'),
  path('professional/support/incidents/<str:incident_id>/', ProfessionalSupportIncidentDetailView.as_view(), name='professional-support-incident-detail'),
  path('professional/profile/', ProfessionalProfileView.as_view(), name='professional-profile'),
  path('professional/profile/visibility/', ProfessionalProfileVisibilityView.as_view(), name='professional-profile-visibility'),
  path('professional/forms-groups/', FormsGroupsOverviewView.as_view(), name='professional-forms-groups'),
  path('professional/forms-groups/lead-form/', ProfessionalLeadFormView.as_view(), name='professional-lead-form'),
  path('professional/forms-groups/lead-form/status/', ProfessionalLeadFormStatusView.as_view(), name='professional-lead-form-status'),
  path('professional/forms-groups/groups/', ProfessionalGroupListView.as_view(), name='professional-groups'),
  path('professional/forms-groups/groups/<int:group_id>/', ProfessionalGroupDetailView.as_view(), name='professional-group-detail'),
  path('professional/forms-groups/groups/<int:group_id>/registration-form/', ClientRegistrationFormView.as_view(), name='professional-group-registration-form'),
  path('professional/forms-groups/groups/<int:group_id>/clients/', GroupClientAccessListView.as_view(), name='professional-group-clients'),
  path('professional/forms-groups/groups/<int:group_id>/import/preview/', GroupImportPreviewView.as_view(), name='professional-group-import-preview'),
  path('professional/forms-groups/groups/<int:group_id>/import/confirm/', GroupImportConfirmView.as_view(), name='professional-group-import-confirm'),
  path('professional/forms-groups/clients/manual/', ManualClientAccessCreateView.as_view(), name='professional-manual-client-create'),
  path('professional/forms-groups/clients/<int:client_id>/', ClientAccessDetailView.as_view(), name='professional-client-detail'),
  path('professional/forms-groups/clients/<int:client_id>/reset-password/', ClientAccessPasswordResetView.as_view(), name='professional-client-reset-password'),
  path('professional/forms-groups/clients/<int:client_id>/grant-access/', ClientAccessGrantPortalAccessView.as_view(), name='professional-client-grant-access'),
  path('professional/forms-groups/clients/<int:client_id>/revoke-access/', ClientAccessRevokePortalAccessView.as_view(), name='professional-client-revoke-access'),
  path('professional/forms-groups/clients/<int:client_id>/status/', ClientAccessStatusView.as_view(), name='professional-client-status'),
  path('professional/forms-groups/clients/<int:client_id>/reset/', ClientAccessResetView.as_view(), name='professional-client-reset'),
  path('professional/forms-groups/clients/<int:client_id>/export/', ClientAccessExportView.as_view(), name='professional-client-export'),
  path('professional/forms-groups/clients/<int:client_id>/delete/', ClientAccessDeleteView.as_view(), name='professional-client-delete'),
  path('professional/forms-groups/clients/<int:client_id>/photo/', ClientAccessPhotoView.as_view(), name='professional-client-photo'),
  path('professional/forms-groups/clients/<int:client_id>/additional-info/', ClientAdditionalInfoView.as_view(), name='professional-client-additional-info'),
  path('professional/forms-groups/clients/<int:client_id>/reminders/', ClientReminderListView.as_view(), name='professional-client-reminders'),
  path('professional/reminders/<int:reminder_id>/', ClientReminderDetailView.as_view(), name='professional-reminder-detail'),
  path('professional/reminders/upcoming/', ProfessionalUpcomingRemindersView.as_view(), name='professional-reminders-upcoming'),
  path('professional/forms-groups/clients/<int:client_id>/progress/', ClientProgressListView.as_view(), name='professional-client-progress'),
  path('professional/progress/<int:entry_id>/', ClientProgressDetailView.as_view(), name='professional-progress-detail'),
  path('professional/forms-groups/pending/<int:submission_id>/', PendingLeadSubmissionView.as_view(), name='professional-pending-form'),
  path('professional/forms-groups/pending/<int:submission_id>/create-client-access/', ClientAccessCreateView.as_view(), name='professional-create-client-access'),
  path('public/forms/<slug:public_slug>/', PublicLeadFormView.as_view(), name='public-lead-form'),
  path('public/forms/<slug:public_slug>/meeting-slots/', PublicLeadMeetingSlotsView.as_view(), name='public-lead-meeting-slots'),
  path('public/forms/<slug:public_slug>/meeting-request/', PublicLeadMeetingRequestView.as_view(), name='public-lead-meeting-request'),
  path('public/group-registration/<slug:public_slug>/', PublicGroupRegistrationView.as_view(), name='public-group-registration'),
  path('professional/password-reset/request-otp/', PasswordResetOtpRequestView.as_view(), name='professional-password-reset-request-otp'),
  path('professional/password-reset/verify-otp/', PasswordResetOtpVerifyView.as_view(), name='professional-password-reset-verify-otp'),
  path('professional/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='professional-password-reset-confirm'),
  path('professional/references/categories/', ProfessionalReferenceCategoryListView.as_view(), name='professional-reference-categories'),
  path('professional/references/categories/<int:category_id>/', ProfessionalReferenceCategoryDetailView.as_view(), name='professional-reference-category-detail'),
  path('professional/references/', ProfessionalReferenceListView.as_view(), name='professional-references'),
  path('professional/references/<int:reference_id>/', ProfessionalReferenceDetailView.as_view(), name='professional-reference-detail'),
  path('professional/templates/standard/', StandardTemplateListView.as_view(), name='professional-standard-templates'),
  path('professional/templates/adopt-standard/', StandardTemplateAdoptView.as_view(), name='professional-adopt-standard-template'),
  path('professional/templates/', TrackingTemplateListView.as_view(), name='professional-templates'),
  path('professional/templates/<int:template_id>/', TrackingTemplateDetailView.as_view(), name='professional-template-detail'),
  path('professional/forms-groups/clients/<int:client_id>/assignments/', ClientTemplateAssignmentListView.as_view(), name='professional-client-assignments'),
  path('professional/forms-groups/clients/<int:client_id>/assignments/<int:assignment_id>/', ClientTemplateAssignmentDetailView.as_view(), name='professional-client-assignment-detail'),
  path('professional/forms-groups/clients/<int:client_id>/entries/', ClientTrackingEntryListView.as_view(), name='professional-client-entries'),
  path('professional/forms-groups/clients/<int:client_id>/notes/', ClientProfessionalNotesView.as_view(), name='professional-client-notes'),
  path('professional/forms-groups/clients/<int:client_id>/change-requests/<int:request_id>/', ProfessionalClientChangeRequestActionView.as_view(), name='professional-client-change-request-action'),
  path('professional/entries/<int:entry_id>/', ProfessionalTrackingEntryDetailView.as_view(), name='professional-entry-detail'),
  path('professional/clients/<int:client_id>/chat/', ProfessionalClientChatView.as_view(), name='professional-client-chat'),
  path('professional/chat/unread/', ProfessionalChatUnreadView.as_view(), name='professional-chat-unread'),
  path('client/change-password/', ClientPasswordChangeView.as_view(), name='client-change-password'),
  path('client/dashboard/', ClientDashboardView.as_view(), name='client-dashboard'),
  path('client/me/', ClientMeView.as_view(), name='client-me'),
  path('client/photo/', ClientPhotoView.as_view(), name='client-photo'),
  path('client/detail-change-request/', ClientDetailChangeRequestView.as_view(), name='client-detail-change-request'),
  path('client/account-deletion-request/', ClientAccountDeletionRequestView.as_view(), name='client-account-deletion-request'),
  path('client/templates/', ClientTemplateListView.as_view(), name='client-templates'),
  path('client/entries/', ClientTrackingEntryView.as_view(), name='client-entries'),
  path('client/entries/<int:entry_id>/', ClientTrackingEntryDetailView.as_view(), name='client-entry-detail'),
  path('client/progress/', ClientPortalProgressView.as_view(), name='client-progress'),
  path('client/chat/', ClientChatView.as_view(), name='client-chat'),
  path('client/chat/unread/', ClientChatUnreadView.as_view(), name='client-chat-unread'),
  path('client/support/incidents/', ClientSupportIncidentListView.as_view(), name='client-support-incidents'),
  path('client/support/incidents/<str:incident_id>/', ClientSupportIncidentDetailView.as_view(), name='client-support-incident-detail'),
  path('errors/report/', ErrorReportView.as_view(), name='error-report'),
]
