from django.urls import path

from .views import (
  ClientAccessCreateView,
  ClientAccessDetailView,
  ClientAccessPasswordResetView,
  GroupClientAccessListView,
  ClientLoginView,
  ClientRegistrationFormView,
  EmailAvailabilityView,
  EmailOtpRequestView,
  EmailOtpVerifyView,
  FormsGroupsOverviewView,
  PendingLeadSubmissionView,
  PasswordResetConfirmView,
  PasswordResetOtpRequestView,
  PasswordResetOtpVerifyView,
  PublicLeadFormView,
  TrainerAccountView,
  TrainerGroupListView,
  TrainerGroupDetailView,
  TrainerLeadFormView,
  TrainerLoginView,
  TrainerLogoutView,
  TrainerPasswordChangeView,
  TrainerProfileStatusView,
  TrainerProfileView,
  TrainerSignupView,
  UsernameAvailabilityView,
)

urlpatterns = [
  path('trainer/check-email/', EmailAvailabilityView.as_view(), name='trainer-check-email'),
  path('trainer/request-email-otp/', EmailOtpRequestView.as_view(), name='trainer-request-email-otp'),
  path('trainer/verify-email-otp/', EmailOtpVerifyView.as_view(), name='trainer-verify-email-otp'),
  path('trainer/check-username/', UsernameAvailabilityView.as_view(), name='trainer-check-username'),
  path('trainer/signup/', TrainerSignupView.as_view(), name='trainer-signup'),
  path('trainer/login/', TrainerLoginView.as_view(), name='trainer-login'),
  path('client/login/', ClientLoginView.as_view(), name='client-login'),
  path('trainer/logout/', TrainerLogoutView.as_view(), name='trainer-logout'),
  path('trainer/account/', TrainerAccountView.as_view(), name='trainer-account'),
  path('trainer/account/change-password/', TrainerPasswordChangeView.as_view(), name='trainer-change-password'),
  path('trainer/profile/status/', TrainerProfileStatusView.as_view(), name='trainer-profile-status'),
  path('trainer/profile/', TrainerProfileView.as_view(), name='trainer-profile'),
  path('trainer/forms-groups/', FormsGroupsOverviewView.as_view(), name='trainer-forms-groups'),
  path('trainer/forms-groups/lead-form/', TrainerLeadFormView.as_view(), name='trainer-lead-form'),
  path('trainer/forms-groups/groups/', TrainerGroupListView.as_view(), name='trainer-groups'),
  path('trainer/forms-groups/groups/<int:group_id>/', TrainerGroupDetailView.as_view(), name='trainer-group-detail'),
  path('trainer/forms-groups/groups/<int:group_id>/registration-form/', ClientRegistrationFormView.as_view(), name='trainer-group-registration-form'),
  path('trainer/forms-groups/groups/<int:group_id>/clients/', GroupClientAccessListView.as_view(), name='trainer-group-clients'),
  path('trainer/forms-groups/clients/<int:client_id>/', ClientAccessDetailView.as_view(), name='trainer-client-detail'),
  path('trainer/forms-groups/clients/<int:client_id>/reset-password/', ClientAccessPasswordResetView.as_view(), name='trainer-client-reset-password'),
  path('trainer/forms-groups/pending/<int:submission_id>/', PendingLeadSubmissionView.as_view(), name='trainer-pending-form'),
  path('trainer/forms-groups/pending/<int:submission_id>/create-client-access/', ClientAccessCreateView.as_view(), name='trainer-create-client-access'),
  path('public/forms/<slug:public_slug>/', PublicLeadFormView.as_view(), name='public-lead-form'),
  path('trainer/password-reset/request-otp/', PasswordResetOtpRequestView.as_view(), name='trainer-password-reset-request-otp'),
  path('trainer/password-reset/verify-otp/', PasswordResetOtpVerifyView.as_view(), name='trainer-password-reset-verify-otp'),
  path('trainer/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='trainer-password-reset-confirm'),
]
