from django.urls import path

from .views import (
  AdminAuditLogListView, AdminDashboardView, AdminErrorLogActionView, AdminErrorLogDetailView,
  AdminErrorLogListView, AdminFinanceView, AdminLoginView, AdminLogoutView, AdminMeView,
  AdminSupportIncidentActionView, AdminSupportIncidentDetailView, AdminSupportIncidentListView,
  AdminAccountLifecycleActionView, AdminAccountLifecycleListView,
  AdminNotificationsView,
  AdminTeamView, AdminTeamMemberView,
  AdminPasswordChangeView,
  AdminCommunicationsView, AdminGlobalSearchView, AdminOperationsView, AdminSystemHealthView,
  AdminSupportAccessView, AdminSupportControlledActionView, AdminUserDirectoryView,
)

urlpatterns = [
  path('login/', AdminLoginView.as_view(), name='admin-portal-login'),
  path('logout/', AdminLogoutView.as_view(), name='admin-portal-logout'),
  path('me/', AdminMeView.as_view(), name='admin-portal-me'),
  path('change-password/', AdminPasswordChangeView.as_view(), name='admin-change-password'),
  path('dashboard/', AdminDashboardView.as_view(), name='admin-portal-dashboard'),
  path('notifications/', AdminNotificationsView.as_view(), name='admin-portal-notifications'),
  path('finance/', AdminFinanceView.as_view(), name='admin-portal-finance'),
  path('operations/', AdminOperationsView.as_view(), name='admin-operations'),
  path('users/', AdminUserDirectoryView.as_view(), name='admin-user-directory'),
  path('communications/', AdminCommunicationsView.as_view(), name='admin-communications'),
  path('health/', AdminSystemHealthView.as_view(), name='admin-system-health'),
  path('search/', AdminGlobalSearchView.as_view(), name='admin-global-search'),
  path('team/', AdminTeamView.as_view(), name='admin-portal-team'),
  path('team/<str:staff_id>/', AdminTeamMemberView.as_view(), name='admin-portal-team-member'),
  path('audit-logs/', AdminAuditLogListView.as_view(), name='admin-portal-audit-logs'),
  path('account-lifecycle/', AdminAccountLifecycleListView.as_view(), name='admin-account-lifecycle'),
  path('account-lifecycle/<str:professional_reference>/action/', AdminAccountLifecycleActionView.as_view(), name='admin-account-lifecycle-action'),
  path('support/incidents/', AdminSupportIncidentListView.as_view(), name='admin-support-incidents'),
  path('support/incidents/<str:incident_id>/', AdminSupportIncidentDetailView.as_view(), name='admin-support-incident-detail'),
  path('support/incidents/<str:incident_id>/action/', AdminSupportIncidentActionView.as_view(), name='admin-support-incident-action'),
  path('support/incidents/<str:incident_id>/access/', AdminSupportAccessView.as_view(), name='admin-support-access'),
  path('support/incidents/<str:incident_id>/controlled-action/', AdminSupportControlledActionView.as_view(), name='admin-support-controlled-action'),
  path('errors/', AdminErrorLogListView.as_view(), name='admin-error-logs'),
  path('errors/<str:error_id>/', AdminErrorLogDetailView.as_view(), name='admin-error-log-detail'),
  path('errors/<str:error_id>/action/', AdminErrorLogActionView.as_view(), name='admin-error-log-action'),
]
